version: "3.9"
















services:
  api1:
    container_name: rest_api_server_1
    build: .
    ports:
      - "5001:5000"
    environment:
      DATABASE_URL: [Credentials]
      FLASK_ENV: development
    depends_on:
      - db








  api2:
    container_name: rest_api_server_2
    build: .
    ports:
      - "5002:5000"
    environment:
      DATABASE_URL: [Credentials]
      FLASK_ENV: development
    depends_on:
      - db
  
  db:
      image: postgres:15
      container_name: rest_api_db
      restart: always
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: [Credentials]
        POSTGRES_DB: students_db
      ports:
        - "5432:5432"
      volumes:
        - pgdata:/var/lib/postgresql/data








  nginx:
    image: nginx:latest
    container_name: rest_api_nginx
    ports:
      - "8080:8080"
    depends_on:
      - api1
      - api2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
















volumes:
  pgdata:























